// android/build.gradle.kts (root project)
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Google services plugin required for Firebase (keep version up-to-date)
        classpath("com.google.gms:google-services:4.3.15")
        // Android Gradle plugin is normally provided by the project generated by Flutter,
        // if you need to override version you can add it here:
        // classpath("com.android.tools.build:gradle:8.1.1")
    }
}

// If you prefer the newer pluginManagement approach, you may also add the plugin to settings.gradle.kts.
// For now classpath + apply plugin at module level is sufficient.

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

/**
 * Custom build directory relocation (kept from your snippet)
 */
val newBuildDir: Directory =
    rootProject.layout.buildDirectory
        .dir("../../build")
        .get()
rootProject.layout.buildDirectory.value(newBuildDir)

subprojects {
    val newSubprojectBuildDir: Directory = newBuildDir.dir(project.name)
    project.layout.buildDirectory.value(newSubprojectBuildDir)
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register<Delete>("clean") {
    delete(rootProject.layout.buildDirectory)
}
